name: Greetings

on:
  workflow_dispatch:
    inputs:
      rgname:
        default: rgdemo
        type: string

# user define
# pre-define variable
# run time variable

jobs:

        
  linuxgreeting:
    name: reply by linux $name

    runs-on: ubuntu-slim
    steps:
      - name: Hello Audience 
        run: echo "Hello Guys What's Up, I'm good ${{ secrets.ANSIBLE_USER }}- ${{ RUNNER.OS}} "
  
