name: Greetings

on:
  workflow_dispatch:
  push:

# user define
# pre-define variable
# run time variable

jobs:

        
  linuxgreeting:
    name: reply by linux $name

    runs-on: ubuntu-slim
    steps:
      - name: Hello Audience 
        run: echo "Hello Guys What's Up, I'm good ${{ github.event.inputs.rgname }}- ${{ RUNNER.OS}} "
  
