name: Greetings

on:
  workflow_dispatch: 

env:
  NAME: 'jitender'

jobs:

        
  linuxgreeting:
    name: reply by linux $name

    runs-on: windows-2022
    steps:
      - name: Hello Audience 
        run: echo "Hello Guys What's Up, I'm good $env:WIN_NAME"
  
