name: Hello Workflow

#none or manual trigger
on: workflow_dispatch 



jobs:
  my_first_job:
    name: My first job
    runs-on: ubuntu-slim
    steps:
      - name: Greeting ${{ env.NAME }}
        run: echo "Hello World from my first Github Action Pipeline created by ${{ vars.NAME }} "
        
   

 
