name: Hello Workflow

#none or manual trigger
on: workflow_dispatch 


jobs:
  my_first_job:
    name: My first job
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Greeting
        run: write-host "Hello World from my first Github Action Pipeline"
        
  my_second_job:
    name: My Second Job
    needs: my_first_job
    runs-on: windows-latest
    steps:
      - name: Greeting
        run: write-host "Hello from Windows"
        
   

 
