name: Infra Setup

on:
  workflow_dispatch:

jobs:
  terraform:
    uses: thejitenderk/reusable-workflow/.github/workflows/practice.yml@main
    with:
      environment: dev
      working_directory: environment
      runner: ubuntu-latest
    secrets:
      azurelogin: ${{ secrets.AZURE_CREDENTIALS }}
