name: Infra Setup

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    uses: thejitenderk/reusable-workflow/.github/workflows/terraform.yml@main
    with:
      environment: dev
      working_directory: environment
      runner: ubuntu-latest
    secrets: inherit
